/*
Isaac Collier
April 14 2020
This program uses custom subroutines to perform math operations and display information to the user
 */

/**
 *
 * @author Isaac
 */
public class frmCreatingYourOwnMethods extends javax.swing.JFrame {

    /**
     * Creates new form frmCreatingYourOwnMethods
     * This class is teaching me about creating and using subroutines
     */
    public frmCreatingYourOwnMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInstArea = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        btnArea = new javax.swing.JButton();
        lblResultsArea = new javax.swing.JLabel();
        lblInstTriAng = new javax.swing.JLabel();
        txtTriAng1 = new javax.swing.JTextField();
        txtTriAng2 = new javax.swing.JTextField();
        btnTriAng = new javax.swing.JButton();
        lblResultsTriAng = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblInstAvg = new javax.swing.JLabel();
        txtAvgNum1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtAvgNum2 = new javax.swing.JTextField();
        txtAvgNum3 = new javax.swing.JTextField();
        txtAvgNum4 = new javax.swing.JTextField();
        btnAvg = new javax.swing.JButton();
        lblResultsAvg = new javax.swing.JLabel();
        lblInstSpeed = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        btnSpeed = new javax.swing.JButton();
        lblResultsSpeed = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblInstCircle = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        btnCircle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblResultsCircle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblInstArea.setForeground(new java.awt.Color(255, 0, 0));
        lblInstArea.setText("Find the area of a rectangle/square. Input the length and width:");

        btnArea.setBackground(new java.awt.Color(255, 0, 0));
        btnArea.setText("Calculate");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        lblInstTriAng.setForeground(new java.awt.Color(0, 0, 255));
        lblInstTriAng.setText("Find the 3rd angle of a triangle. Input the other two angles:");

        btnTriAng.setBackground(new java.awt.Color(0, 0, 255));
        btnTriAng.setText("Calculate");
        btnTriAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriAngActionPerformed(evt);
            }
        });

        lblInstAvg.setForeground(new java.awt.Color(204, 0, 204));
        lblInstAvg.setText("Find the average of 4 inputted numbers:");

        btnAvg.setBackground(new java.awt.Color(204, 0, 204));
        btnAvg.setText("Calculate");
        btnAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgActionPerformed(evt);
            }
        });

        lblInstSpeed.setForeground(new java.awt.Color(255, 102, 0));
        lblInstSpeed.setText("Find the speed of an object. Input the distance( in metres) it went first and the time it took second(in seconds):");

        btnSpeed.setBackground(new java.awt.Color(255, 102, 0));
        btnSpeed.setText("Calculate");
        btnSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeedActionPerformed(evt);
            }
        });

        lblInstCircle.setForeground(new java.awt.Color(255, 255, 0));
        lblInstCircle.setText("Find the circumference of a circle. Input the radius of the circle:");

        btnCircle.setBackground(new java.awt.Color(255, 255, 0));
        btnCircle.setText("Calculate");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        jLabel12.setText("Math operations with custom subroutines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstArea)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnArea)
                                .addGap(18, 18, 18)
                                .addComponent(lblResultsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInstTriAng, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTriAng1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTriAng2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTriAng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultsTriAng, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInstAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInstSpeed)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultsSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInstCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCircle))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultsCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAvgNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAvgNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAvgNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAvgNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAvg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultsAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(219, 219, 219))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(lblInstArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea)
                    .addComponent(lblResultsArea))
                .addGap(18, 18, 18)
                .addComponent(lblInstTriAng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTriAng1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTriAng2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTriAng)
                    .addComponent(lblResultsTriAng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstAvg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvgNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvgNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvgNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvgNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvg)
                    .addComponent(lblResultsAvg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstSpeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeed)
                    .addComponent(lblResultsSpeed))
                .addGap(11, 11, 11)
                .addComponent(lblInstCircle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCircle)
                    .addComponent(lblResultsCircle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//subroutine for area operation
    public static double Area (double length,double width)
{
    //multiplies length by width
    double area = length * width;
    //brings area value back to program
    return (area);
  
}

    //subroutine for 3rd angle operation
public static double TriAng (double ang1,double ang2)
{
    //finds third angle of a triangle
    double ang3 = 180 - (ang1 + ang2);
    //brings 3rd angle value back to program
    return (ang3);
  
}    
 
 //subroutine for average operation
public static double Avg (double num1,double num2, double num3, double num4)
{
    //finds average of 4 numbers
    double average = (num1 + num2 + num3 + num4)/4;
    //brings average value back to program
    return (average);
  
}

//subroutine for speed operation
public static double Speed (double distance,double time)
{
    //finds speed
    double speed = distance/time;
    //brings speed value back to program
    return (speed);
  
}

//subroutine for circumference operation
public static double Circle (double radius)
{
    //finds circumference
    double circumference = 2*radius*3.14159;
    //brings circumference value back to program
    return (circumference);
  
}

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
     //gets values from what user put into textfields
        double length = Double.parseDouble(txtLength.getText());
        double width = Double.parseDouble(txtWidth.getText());
 //declares a variable
        double area;
        //sends program to subroutine
      area =  Area(length,width);
          //displays result to the user
         lblResultsArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnTriAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriAngActionPerformed
    //gets values from what user put into textfields
        double ang1 = Double.parseDouble(txtTriAng1.getText());
        double ang2 = Double.parseDouble(txtTriAng2.getText());
         //declares a variable
 double ang3;
   //sends program to subroutine
      ang3 =  TriAng(ang1,ang2);
             //displays result to the user
         lblResultsTriAng.setText(String.valueOf(ang3));
    }//GEN-LAST:event_btnTriAngActionPerformed

    private void btnAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgActionPerformed
       //gets values from what user put into textfields
        double num1 = Double.parseDouble(txtAvgNum1.getText());
        double num2 = Double.parseDouble(txtAvgNum2.getText());
         double num3 = Double.parseDouble(txtAvgNum3.getText());
        double num4 = Double.parseDouble(txtAvgNum4.getText());
         //declares a variable
 double average;
   //sends program to subroutine
      average =  Avg(num1,num2,num3,num4);
             //displays result to the user
         lblResultsAvg.setText(String.valueOf(average));
    }//GEN-LAST:event_btnAvgActionPerformed

    private void btnSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeedActionPerformed
       //gets values from what user put into textfields
        double distance = Double.parseDouble(txtDistance.getText());
        double time = Double.parseDouble(txtTime.getText());
         //declares a variable
 double speed;
   //sends program to subroutine
      speed =  Speed(distance,time);
             //displays result to the user
         lblResultsSpeed.setText(String.valueOf(speed));
    }//GEN-LAST:event_btnSpeedActionPerformed

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
   //gets a value from what user put into the textfield
        double radius = Double.parseDouble(txtRadius.getText());
         //declares a variable
 double circumference;
   //sends program to subroutine
      circumference =  Circle(radius);
             //displays result to the user
         lblResultsCircle.setText(String.valueOf(circumference));
    }//GEN-LAST:event_btnCircleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreatingYourOwnMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreatingYourOwnMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreatingYourOwnMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreatingYourOwnMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCreatingYourOwnMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnAvg;
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnSpeed;
    private javax.swing.JButton btnTriAng;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblInstArea;
    private javax.swing.JLabel lblInstAvg;
    private javax.swing.JLabel lblInstCircle;
    private javax.swing.JLabel lblInstSpeed;
    private javax.swing.JLabel lblInstTriAng;
    private javax.swing.JLabel lblResultsArea;
    private javax.swing.JLabel lblResultsAvg;
    private javax.swing.JLabel lblResultsCircle;
    private javax.swing.JLabel lblResultsSpeed;
    private javax.swing.JLabel lblResultsTriAng;
    private javax.swing.JTextField txtAvgNum1;
    private javax.swing.JTextField txtAvgNum2;
    private javax.swing.JTextField txtAvgNum3;
    private javax.swing.JTextField txtAvgNum4;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTriAng1;
    private javax.swing.JTextField txtTriAng2;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
